# Generated by Django 5.0.4 on 2024-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
