# Generated by Django 5.0.4 on 2024-04-17 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
