# Generated by Django 5.0.4 on 2024-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='unknown', max_length=20, unique=True),
        ),
    ]
