# Generated by Django 5.0.4 on 2024-04-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parking_id'),
        ('user', '0002_remove_user_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
