# Generated by Django 5.0.4 on 2024-04-18 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_parking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
