# Generated by Django 5.0.4 on 2024-04-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_parking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='model',
            new_name='car_model',
        ),
    ]
